# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReimbursementButler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReimbursementButler
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  platform :ios, '13.0'

end
